export default {
  'api.login': '/login',
  'api.me': '/api/me',
  'api.users.create': '/api/users',
  'api.doctors': '/api/doctors',
  'api.doctors.create': '/api/doctors',
  'api.doctors.update': '/api/doctors/{doctorId}',
  'api.doctors.search': '/api/doctors/search',
  'api.doctors.paged.search': '/api/doctors/paged/search',
  'api.specializations': '/api/specializations',
  'api.specializations.search': '/api/specializations/search',
  'api.specializations.all': '/api/specializations/all',
  'api.hospitals': '/api/hospitals',
  'api.hospitals.all': '/api/hospitals/all',
  'api.hospitals.create': '/api/hospitals',
  'api.hospitals.search': '/api/hospitals/search',
  'api.healthchecks': '/api/users/{userId}/healthchecks',
  'api.healthchecks.user.search': '/api/users/{userId}/healthchecks/search',
  'api.healthchecks.create': '/api/healthchecks',
  'api.healthchecks.update': '/api/healthchecks/update',
  'api.healthchecks.delete': '/api/healthchecks/{healthCheckId}',
  'api.healthchecks.search': '/api/healthchecks/search',
  'api.healthchecks.get_healthcheck': '/api/user/healthchecks/{healthCheckId}',
  'api.file_upload': '/api/s3upload/{userId}/{healthCheckId}',
  'api.reports.create': '/api/reports',
  'api.reports.delete': '/api/reports/{reportId}',
}
